version: '3'
services:
  backend:
    build: ./ficohsa_items_backend
    ports:
      - "8081:8080"
    networks:
      - internal_network
  front:
    build: ./ficohsa_items_front
    depends_on:
      - backend
    ports:
      - "80:3000"
    networks:
      - internal_network

networks:
  internal_network:
