spring:
  application:
    name: max-integer-solver
    title: max-integer-solver
  h2:
    console:
      enabled: true
  datasource-h2:
    url: jdbc:h2:mem:ficohsa_item;DB_CLOSE_DELAY=-1
    driverClassName: "org.h2.Driver"
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  servlet:
    context-path: /api/v1

springdoc:
  show-actuator: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include:  openapi, swagger-ui

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
